#%RAML 0.8
---
title: Álainn Cosmetics API
version: v1.0
#baseUri: http://alainn-cosmetics.cloudhub.io/api/{version}
baseUri: http://mocksvc.mulesoft.com/mocks/e5688a09-223b-4158-be8d-c8789f8e1b7a/api/{version}
schemas:
  - item: &item-schema |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "links" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "properties" : {
                "href" : { "type" : "string" },
                "label" : { "type" : "string" },
                "rel" : { "type" : "string" }
              }
            }
          },
          "id" : { "type" : "string" },
          "name" : { "type" : "string" },
          "summary" : { "type" : "string" },
          "type" : { "type" : "string" },
          "description" : { "type" : "string" },
          "skus" : {
            "type" : "object",
            "properties" : {
              "collection" : {
                "type" : "array",
                "items" : {
                  "type" : "object",
                  "properties" : {
                    "links" : {
                      "type" : "array",
                      "items" : {
                        "type" : "object",
                        "properties" : {
                          "href" : { "type" : "string" },
                          "label" : { "type" : "string" },
                          "rel" : { "type" : "string" }
                        }
                      }
                    },
                    "id" : { "type" : "long" },
                    "type" : { "type" : "string" },
                    "name" : { "type" : "string" },
                    "summary" : { "type" : "string" },
                    "sku" : { "type" : "string" },
                    "price" : { "type" : "number" },  
                    "stockQuantity" : { "type" : "integer" },
                    "characteristics" : {
                      "type" : "array",
                      "items" : {
                        "type" : "object",
                        "properties" : {
                          "name" : { "type" : "string" },
                          "value" : { "type" : "string" }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }    
      }
  - items: &items-schema |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "collection" : {
            "type" : "object",
            "properties" : {
              "links" : {
                "type" : "array",
                "items" : {
                  "type" : "object",
                  "properties" : {
                    "href" : { "type" : "string" },
                    "label" : { "type" : "string" },
                    "rel" : { "type" : "string" }
                  }
                }
              },
              "items" : {
                "type" : "array",
                "items" : {
                  "type" : "object",
                  "properties" : {
                      "id" : { "type" : "long" },
                      "type" : { "type" : "string" },
                      "name" : { "type" : "string" },
                      "summary" : { "type" : "string" }
                  }
                }
              }
            }
          }
        }    
      }
  - pending-order: *item-schema
  - pending-orders: *items-schema
  - reviews: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "count" : { "type" : "integer" },
          "reviews" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "properties" : {
                  "id" : { "type" : "string" },
                  "author" : { "type" : "string" },
                  "review" : { "type" : "string" }
              }
            }
          }
        }    
      }
  - review-request: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "review" : { "type" : "string" }

        }    
      }
  - top-items: *items-schema
  - top-brands: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "count" : { "type" : "integer" },
          "brands" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "properties" : {
                  "id" : { "type" : "string" },
                  "name" : { "type" : "string" }
              }
            }
          }
        }    
      }
  - recommendations: *items-schema
  - promotions: *items-schema
  - promotion: *item-schema  
  - wish-list: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "wishes" : {
            "type" : "array",
            "items" : {
              "type" : "object",
              "properties" : {
                  "sku" : { "type" : "string" },
                  "name" : { "type" : "string" },
                  "summary" : { "type" : "string" }
              }
            }
          }
        }    
      }
  - wish-list-request: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "sku" : { "type" : "string" }
        }
      }
  - basket: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "items" : {
            "type" : "array",
            "items" : { 
              "type" : "object",
              "properties" : {
                "sku" : { "type" : "string" },
                "name" : { "type" : "string" },
                "price" : { "type" : "number" },
                "quantity" : { "type" : "integer" }
              }
             }
          }
        }
      }
  - basket-item: &basket-item-schema | 
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "sku" : { "type" : "string" },
          "name" : { "type" : "string" },
          "quantity" : { "type" : "integer" }
        }
      }
  - skus: *basket-item-schema
  - orders: | 
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "date" : { "type" : "date" },
          "total" : { "type" : "number" },
          "pickupLocation" : { "type" : "string" }
        }
      }
  - order: | 
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "date" : { "type" : "date" },
          "total" : { "type" : "number" },
          "discount" : { "type" : "number" },
          "pickupLocation" : { "type" : "string" },
          "collection" : {
            "type" : "array",
            "items" : { 
              "type" : "object",
              "properties" : {
                "links" : {
                  "type" : "array",
                  "items" : {
                    "type" : "object",
                    "properties" : {
                      "href" : { "type" : "string" },
                      "label" : { "type" : "string" },
                      "rel" : { "type" : "string" }
                    }
                  }
                },
                "sku" : { "type" : "string" },
                "name" : { "type" : "string" },
                "price" : { "type" : "number" },
                "quantity" : { "type" : "integer" },
                "status" : { "type" : "string" }
              }
             }
          }
        }
      }
  - order-request: &order-request-schema |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "pickupLocation" : { "type" : "string" },
          "items" : {
            "type" : "array",
            "items" : { 
              "type" : "object",
              "properties" : {
                "sku" : { "type" : "string" },
                "quantity" : { "type" : "integer" }
              }
             }
          }
        }
      }
  - return-request: *order-request-schema
  - sale: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "date" : { "type" : "date" },
          "total" : { "type" : "number" },
          "discount" : { "type" : "number" },
          "items" : {
            "type" : "array",
            "items" : { 
              "type" : "object",
              "properties" : {
                "sku" : { "type" : "string" },
                "name" : { "type" : "string" },
                "price" : { "type" : "number" },
                "quantity" : { "type" : "integer" }
              }
            }
          }
        }
      }
  - sales: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "date" : { "type" : "date" },
          "total" : { "type" : "number" }
        }
      }
  - sale-request: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "items" : {
            "type" : "array",
            "items" : { 
              "type" : "object",
              "properties" : {
                "sku" : { "type" : "string" },
                "quantity" : { "type" : "integer" }
              }
             }
          }
        }
      }
  - registration-request: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "firstName" : { "type" : "string" },
          "lastName" : { "type" : "string" },
          "mobileNumber" : { "type" : "string" },
          "notificationPreferences": {
            "type" : "array",
            "items" : { "type" : "string" }
          }
        }
      }
  - mobile-token-request: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "token" : { "type" : "string" }
        }
      }
  - mobile-tokens: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "tokens" : { 
            "type" : "array",
            "items" : { "type" : "string" } 
          }
        }
      }
  - my-profile: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "x-user-id" : { "type" : "string" },
          "firstName" : { "type" : "string" },
          "lastName" : { "type" : "string" },
          "notificationPreferences" : { 
            "type" : "array",
            "items" : { "type" : "string" } 
          }
        }
      }
documentation:
  - title: Introduction
    content: |
      API to act as main point of entry to multi-channel software so that the customer gets a consistent experience across all channels. 
      
      * A
      * B
      * C
traits:
  - personal:
      headers:
        x-user-id:
          type: string
          required: true
          example: 4322234
  - pageable:
      queryParameters:
        pageIndex:
          type: integer
          default: 0
          example: 0
          required: false
        pageSize:
          type: integer
          default: 10
          example: 10
          required: false
  - searchable:
      queryParameters:
        name:
          type: string
          required: false
          example: Deep Steep Honey Bubble Bath
        type:
          type: string
          required: false
          example: Oils
        brand:
          type: string
          required: false
          example: Naturtint
  - imageable:
      queryParameters:
        imageType:
          description: Comma , separated list just like in example. One alone may be present
          type: string
          required: false
          default: SmallImage
          example: TinyImage,SwatchImage,SmallImage,MediumImage,LargeImage
resourceTypes: 
  - document:
      get:
        responses:
          200:
            body:
              application/json:
                schema: <<schema>>
  - read-only-collection:
      type: { document : { schema : <<resourcePathName>> } }
      get:
        is: [pageable]
  - collection:
      type: read-only-collection
      post:
        body:
          application/json:
            schema: <<resourcePathName | !singularize>>-request  # e.g. order
        responses: &postResponse
          201:
            description: Created!
            headers:
              Location:
                description: uri of new resource
                type: string
                required: true  
  - controller:
      post:
        responses:
          204:
            description: Done!
  - member:
      type: { document : { schema : <<resourcePathName | !singularize >> } }
      put?:
        body:
          application/json:
            schema: <<resourcePathName>>
        responses:
          204:
            description: Modified
      patch?:
        body:
          application/json:
            schema: <<resourcePathName | !singularize>>
      delete?:
        responses:
          204:
            description: Deleted
/items:
  type: read-only-collection
  description: List of all items on sale
  get:
    is: [searchable, imageable]
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "links": [
                      {
                          "href": "https://localhost:8082/omni-channel-api/v1.0?pageIndex=28&pageSize=7",
                          "rel": "next"
                      },
                      {
                          "href": "https://localhost:8082/omni-channel-api/v1.0?pageIndex=14&pageSize=7",
                          "rel": "prev"
                      },
                      {
                          "href": "https://localhost:8082/omni-channel-api/v1.0/items",
                          "rel": "self"
                      }
                  ],
                  "collection": {
                      "size": 7,
                      "items": [
                          {
                              "id": "B003Y60XCC",
                              "type": "Chemical Hair Dyes",
                              "name": "L'Oreal Oreor 30 Volume Creme Developer",
                              "summary": "Fully stabilized formula - Freshness assured",
                              "brand": "L'Oreal Paris",
                              "links": [
                                  {
                                      "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003Y60XCC",
                                      "rel": "self"
                                  },
                                  {
                                      "href": "http://ecx.images-amazon.com/images/I/41MWX6KNAuL._SL75_.jpg",
                                      "rel": "SmallImage"
                                  }
                              ]
                          },
                          {
                              "id": "B0044D30Z6",
                              "type": "Chemical Hair Dyes",
                              "name": "Garnier HerbaShine Color Creme with Bamboo Extract",
                              "summary": "",
                              "brand": "Garnier",
                              "links": [
                                  {
                                      "href": "https://localhost:8082/omni-channel-api/v1.0/items/B0044D30Z6",
                                      "rel": "self"
                                  },
                                  {
                                      "href": "http://ecx.images-amazon.com/images/I/31I7w6YQ5eL._SL75_.jpg",
                                      "rel": "SmallImage"
                                  }
                              ]
                          },
                          {
                              "id": "B0042YK9F6",
                              "type": "Bath Pearls & Flakes",
                              "name": "Pearlcium Pearl Powder",
                              "summary": "",
                              "brand": "TheraPure Health Essentials",
                              "links": [
                                  {
                                      "href": "https://localhost:8082/omni-channel-api/v1.0/items/B0042YK9F6",
                                      "rel": "self"
                                  },
                                  {
                                      "href": "http://ecx.images-amazon.com/images/I/316RsE4g09L._SL75_.jpg",
                                      "rel": "SmallImage"
                                  }
                              ]
                          },
                          {
                              "id": "B004CDNSBO",
                              "type": "Oils",
                              "name": "100% Pure Evening Primrose Oil",
                              "summary": "",
                              "brand": "Now Foods",
                              "links": [
                                  {
                                      "href": "https://localhost:8082/omni-channel-api/v1.0/items/B004CDNSBO",
                                      "rel": "self"
                                  },
                                  {
                                      "href": "http://ecx.images-amazon.com/images/I/11B-tmUqh5L._SL75_.jpg",
                                      "rel": "SmallImage"
                                  }
                              ]
                          },
                          {
                              "id": "B0043C8SPK",
                              "type": "Chemical Hair Dyes",
                              "name": "TouchBack Temporary Color Marker",
                              "summary": "Won't flake or rub off when brushed",
                              "brand": "ColorMark",
                              "links": [
                                  {
                                      "href": "https://localhost:8082/omni-channel-api/v1.0/items/B0043C8SPK",
                                      "rel": "self"
                                  },
                                  {
                                      "href": "http://ecx.images-amazon.com/images/I/31dGyu4hQJL._SL75_.jpg",
                                      "rel": "SmallImage"
                                  }
                              ]
                          },
                          {
                              "id": "B003Y6182G",
                              "type": "Chemical Hair Dyes",
                              "name": "L' Oreal Oreor 40-Volume Creme Developer",
                              "summary": "Beautiful, uniform color",
                              "brand": "L'Oreal Paris",
                              "links": [
                                  {
                                      "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003Y6182G",
                                      "rel": "self"
                                  },
                                  {
                                      "href": "http://ecx.images-amazon.com/images/I/41GDOvgw1KL._SL75_.jpg",
                                      "rel": "SmallImage"
                                  }
                              ]
                          },
                          {
                              "id": "B004ECF7LC",
                              "type": "Chemical Hair Dyes",
                              "name": "L'Oreal Paris Excellence Crème with Pro-Keratine Complex",
                              "summary": "",
                              "brand": "L'Oreal Paris",
                              "links": [
                                  {
                                      "href": "https://localhost:8082/omni-channel-api/v1.0/items/B004ECF7LC",
                                      "rel": "self"
                                  },
                                  {
                                      "href": "http://ecx.images-amazon.com/images/I/21g%2B2DBWK1L._SL75_.jpg",
                                      "rel": "SmallImage"
                                  }
                              ]
                          }
                      ]
                  }
              }
  /{item}:
    get:
      is: [imageable]
      responses:
        200:
          body:
            application/json:
              example: |
                {
                    "links": [
                        {
                            "href": "https://localhost:8082/omni-channel-api/v1.0/items/B0044D30Z6",
                            "rel": "self"
                        }
                    ],
                    "id": "B0044D30Z6",
                    "type": "Chemical Hair Dyes",
                    "name": "Garnier HerbaShine Color Creme with Bamboo Extract",
                    "brand": "Garnier",
                    "skus": {
                        "size": 15,
                        "items": [
                            {
                                "id": "B003JTE8JS",
                                "name": "Garnier Herbashine Haircolor, 630 Light Golden Brown",
                                "summary": "Only 10 minutes",
                                "price": 15.98,
                                "sku": "B003JTE8JS",
                                "stockQuantity": 3,
                                "links": [
                                    {
                                        "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003JTE8JS",
                                        "rel": "self"
                                    },
                                    {
                                        "href": "http://ecx.images-amazon.com/images/I/517QdA0lU9L._SL75_.jpg",
                                        "rel": "SmallImage"
                                    }
                                ]
                            },
                            {
                                "id": "B003JTGCRE",
                                "name": "Garnier HerbaShine Color Creme, with Bamboo Extract, Dark Natural, Brown 400",
                                "summary": "Used For: Hair Color",
                                "price": 12.98,
                                "sku": "B003JTGCRE",
                                "stockQuantity": 3,
                                "links": [
                                    {
                                        "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003JTGCRE",
                                        "rel": "self"
                                    },
                                    {
                                        "href": "http://ecx.images-amazon.com/images/I/610m3duxPEL._SL75_.jpg",
                                        "rel": "SmallImage"
                                    }
                                ]
                            },
                            {
                                "id": "B0044B4KTI",
                                "name": "Garnier Herbashine Haircolor, 426 Dark Burgundy",
                                "summary": "Only 10 minutes",
                                "price": 15.98,
                                "sku": "B0044B4KTI",
                                "stockQuantity": 3,
                                "links": [
                                    {
                                        "href": "https://localhost:8082/omni-channel-api/v1.0/items/B0044B4KTI",
                                        "rel": "self"
                                    },
                                    {
                                        "href": "http://ecx.images-amazon.com/images/I/51bmY9mcQ4L._SL75_.jpg",
                                        "rel": "SmallImage"
                                    }
                                ]
                            },
                            {
                                "id": "B003JTA1IU",
                                "name": "Garnier Herbashine Haircolor, 645 Copper Mahogany Brown",
                                "summary": "Only 10 minutes",
                                "price": 15.98,
                                "sku": "B003JTA1IU",
                                "stockQuantity": 3,
                                "links": [
                                    {
                                        "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003JTA1IU",
                                        "rel": "self"
                                    },
                                    {
                                        "href": "http://ecx.images-amazon.com/images/I/51ZLparVUKL._SL75_.jpg",
                                        "rel": "SmallImage"
                                    }
                                ]
                            },
                            {
                                "id": "B003JTE9DS",
                                "name": "Garnier Herbashine Haircolor, 200 Soft Black",
                                "summary": "Only 10 minutes",
                                "price": 15.98,
                                "sku": "B003JTE9DS",
                                "stockQuantity": 3,
                                "links": [
                                    {
                                        "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003JTE9DS",
                                        "rel": "self"
                                    },
                                    {
                                        "href": "http://ecx.images-amazon.com/images/I/51eScnw7yvL._SL75_.jpg",
                                        "rel": "SmallImage"
                                    }
                                ]
                            },
                            {
                                "id": "B003JTGDRI",
                                "name": "Garnier Herbashine Haircolor, 800 Medium Natural Blonde",
                                "summary": "Only 10 minutes",
                                "price": 15.98,
                                "sku": "B003JTGDRI",
                                "stockQuantity": 3,
                                "links": [
                                    {
                                        "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003JTGDRI",
                                        "rel": "self"
                                    },
                                    {
                                        "href": "http://ecx.images-amazon.com/images/I/51FoXQ8NmsL._SL75_.jpg",
                                        "rel": "SmallImage"
                                    }
                                ]
                            },
                            {
                                "id": "B003JTKXI8",
                                "name": "Garnier Herbashine Haircolor, 565 Medium Auburn Brown",
                                "summary": "Only 10 minutes",
                                "price": 15.98,
                                "sku": "B003JTKXI8",
                                "stockQuantity": 3,
                                "links": [
                                    {
                                        "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003JTKXI8",
                                        "rel": "self"
                                    },
                                    {
                                        "href": "http://ecx.images-amazon.com/images/I/51xaz3QTpuL._SL75_.jpg",
                                        "rel": "SmallImage"
                                    }
                                ]
                            },
                            {
                                "id": "B003JTA108",
                                "name": "HERBASHINE #535 MED GOLD MAHOG Size: KIT",
                                "summary": "",
                                "price": 15.98,
                                "sku": "B003JTA108",
                                "stockQuantity": 3,
                                "links": [
                                    {
                                        "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003JTA108",
                                        "rel": "self"
                                    },
                                    {
                                        "href": "http://ecx.images-amazon.com/images/I/51aDQYhAcLL._SL75_.jpg",
                                        "rel": "SmallImage"
                                    }
                                ]
                            },
                            {
                                "id": "B0046HDOAQ",
                                "name": "Garnier Herbashine Haircolor, 415 Soft Mahogany Dark Brown",
                                "summary": "Only 10 minutes",
                                "price": 15.98,
                                "sku": "B0046HDOAQ",
                                "stockQuantity": 3,
                                "links": [
                                    {
                                        "href": "https://localhost:8082/omni-channel-api/v1.0/items/B0046HDOAQ",
                                        "rel": "self"
                                    },
                                    {
                                        "href": "http://ecx.images-amazon.com/images/I/51Mm0-S5hkL._SL75_.jpg",
                                        "rel": "SmallImage"
                                    }
                                ]
                            },
                            {
                                "id": "B003JTGCUQ",
                                "name": "Garnier Herbashine Haircolor, 600 Light Natural Brown",
                                "summary": "Only 10 minutes",
                                "price": 15.98,
                                "sku": "B003JTGCUQ",
                                "stockQuantity": 3,
                                "links": [
                                    {
                                        "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003JTGCUQ",
                                        "rel": "self"
                                    },
                                    {
                                        "href": "http://ecx.images-amazon.com/images/I/51z9fid7g9L._SL75_.jpg",
                                        "rel": "SmallImage"
                                    }
                                ]
                            },
                            {
                                "id": "B003JTC5F2",
                                "name": "Garnier Herbashine Haircolor, 700 Dark Natural Blonde",
                                "summary": "Only 10 minutes",
                                "price": 15.98,
                                "sku": "B003JTC5F2",
                                "stockQuantity": 3,
                                "links": [
                                    {
                                        "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003JTC5F2",
                                        "rel": "self"
                                    },
                                    {
                                        "href": "http://ecx.images-amazon.com/images/I/51w-bVxOS9L._SL75_.jpg",
                                        "rel": "SmallImage"
                                    }
                                ]
                            },
                            {
                                "id": "B003JTC5DO",
                                "name": "Garnier Herbashine Haircolor, 900 Light Natural Blonde",
                                "summary": "Only 10 minutes",
                                "price": 15.98,
                                "sku": "B003JTC5DO",
                                "stockQuantity": 3,
                                "links": [
                                    {
                                        "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003JTC5DO",
                                        "rel": "self"
                                    },
                                    {
                                        "href": "http://ecx.images-amazon.com/images/I/41eHG4l9lPL._SL75_.jpg",
                                        "rel": "SmallImage"
                                    }
                                ]
                            },
                            {
                                "id": "B003JTE8IE",
                                "name": "Garnier Herbashine Haircolor 500 Medium Natural Brown",
                                "summary": "",
                                "price": 15.98,
                                "sku": "B003JTE8IE",
                                "stockQuantity": 3,
                                "links": [
                                    {
                                        "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003JTE8IE",
                                        "rel": "self"
                                    },
                                    {
                                        "href": "http://ecx.images-amazon.com/images/I/51gwe6aDeHL._SL75_.jpg",
                                        "rel": "SmallImage"
                                    }
                                ]
                            },
                            {
                                "id": "B003JTE8MA",
                                "name": "Garnier Herbashine Haircolor, 530 Medium Golden Brown",
                                "summary": "Only 10 minutes",
                                "price": 15.98,
                                "sku": "B003JTE8MA",
                                "stockQuantity": 3,
                                "links": [
                                    {
                                        "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003JTE8MA",
                                        "rel": "self"
                                    },
                                    {
                                        "href": "http://ecx.images-amazon.com/images/I/51knnh-UAeL._SL75_.jpg",
                                        "rel": "SmallImage"
                                    }
                                ]
                            },
                            {
                                "id": "B003JTC5AM",
                                "name": "Garnier Herbashine Haircolor, 510 Medium Ash Brown",
                                "summary": "Only 10 minutes",
                                "price": 15.98,
                                "sku": "B003JTC5AM",
                                "stockQuantity": 3,
                                "links": [
                                    {
                                        "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003JTC5AM",
                                        "rel": "self"
                                    },
                                    {
                                        "href": "http://ecx.images-amazon.com/images/I/51NbVktFgOL._SL75_.jpg",
                                        "rel": "SmallImage"
                                    }
                                ]
                            }
                        ]
                    }
                }
    /reviews:
      type: read-only-collection
      description: Third party reviews for this item
    /skus:
      type: read-only-collection
      get:
        is: [searchable]
        responses:
          200:
            body:
              application/json:
                example: |
                  {
                    "collection" : {
                      "links" : [
                        { "rel" : "next", "href" : "" },
                        { "rel" : "prev", "href" : "" },
                        { "rel" : "self", "href" : "" }
                      ],
                      "items" : [
                        {
                          "links" : [
                            { "rel" : "image", "href" : "" },
                            { "rel" : "self", "href" : "" },
                            { "rel" : "parent", "label" :"General Info", "href" : "" }
                          ],
                          "id" : "12343214",
                          "sku" : "12344",
                          "price" : 1.00,
                          "stockQuantity" : 1
                        },
                        {
                          "links" : [
                            { "rel" : "image", "href" : "" },
                            { "rel" : "self", "href" : "" }
                            { "rel" : "parent", "label" :"General Info", "href" : "" }                
                          ],
                          "id" : "12343214",
                          "sku" : "12344",
                          "price" : 2.00,
                          "stockQuantity" : 10
                        }
                      ]
                    }
                  }
      /{sku}:
        get:
          responses:
            200:
              body:
                application/json:
                  example: |
                    {
                      "links" : [
                        { "rel" : "image", "href" : "" },
                        { "rel" : "self", "href" : "" },
                        { "rel" : "parent", "href" : "" }
                      ],
                      "id" : "12343214",
                      "sku" : "12344",
                      "price" : 1.00,
                      "stockQuantity" : 1,
                      "characteristics" : [
                        { "name" : "size", "value" : "large" },
                        { "name" : "color", "value" : "blue" }
                      ]
                    }
/wish-list:
  type: collection
  is: [personal]
  post:
    description: Add an Item to my Wish List.
    body:
      application/json:
        example: |
          {
            "sku" : "B004GW14E4"
          }
  get:
    is: [imageable]
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "links": [
                      {
                          "href": "https://localhost:8082/omni-channel-api/v1.0?pageIndex=28&pageSize=7",
                          "rel": "next"
                      },
                      {
                          "href": "https://localhost:8082/omni-channel-api/v1.0?pageIndex=14&pageSize=7",
                          "rel": "prev"
                      },
                      {
                          "href": "https://localhost:8082/omni-channel-api/v1.0/items",
                          "rel": "self"
                      }
                  ],
                  "collection": {
                      "size": 7,
                      "items": [
                          {
                              "id": "B003Y60XCC",
                              "type": "Chemical Hair Dyes",
                              "name": "L'Oreal Oreor 30 Volume Creme Developer",
                              "summary": "Fully stabilized formula - Freshness assured",
                              "brand": "L'Oreal Paris",
                              "links": [
                                  {
                                      "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003Y60XCC",
                                      "rel": "self"
                                  },
                                  {
                                      "href": "http://ecx.images-amazon.com/images/I/41MWX6KNAuL._SL75_.jpg",
                                      "rel": "SmallImage"
                                  }
                              ]
                          },
                          {
                              "id": "B0044D30Z6",
                              "type": "Chemical Hair Dyes",
                              "name": "Garnier HerbaShine Color Creme with Bamboo Extract",
                              "summary": "",
                              "brand": "Garnier",
                              "links": [
                                  {
                                      "href": "https://localhost:8082/omni-channel-api/v1.0/items/B0044D30Z6",
                                      "rel": "self"
                                  },
                                  {
                                      "href": "http://ecx.images-amazon.com/images/I/31I7w6YQ5eL._SL75_.jpg",
                                      "rel": "SmallImage"
                                  }
                              ]
                          },
                          {
                              "id": "B0042YK9F6",
                              "type": "Bath Pearls & Flakes",
                              "name": "Pearlcium Pearl Powder",
                              "summary": "",
                              "brand": "TheraPure Health Essentials",
                              "links": [
                                  {
                                      "href": "https://localhost:8082/omni-channel-api/v1.0/items/B0042YK9F6",
                                      "rel": "self"
                                  },
                                  {
                                      "href": "http://ecx.images-amazon.com/images/I/316RsE4g09L._SL75_.jpg",
                                      "rel": "SmallImage"
                                  }
                              ]
                          },
                          {
                              "id": "B004CDNSBO",
                              "type": "Oils",
                              "name": "100% Pure Evening Primrose Oil",
                              "summary": "",
                              "brand": "Now Foods",
                              "links": [
                                  {
                                      "href": "https://localhost:8082/omni-channel-api/v1.0/items/B004CDNSBO",
                                      "rel": "self"
                                  },
                                  {
                                      "href": "http://ecx.images-amazon.com/images/I/11B-tmUqh5L._SL75_.jpg",
                                      "rel": "SmallImage"
                                  }
                              ]
                          },
                          {
                              "id": "B0043C8SPK",
                              "type": "Chemical Hair Dyes",
                              "name": "TouchBack Temporary Color Marker",
                              "summary": "Won't flake or rub off when brushed",
                              "brand": "ColorMark",
                              "links": [
                                  {
                                      "href": "https://localhost:8082/omni-channel-api/v1.0/items/B0043C8SPK",
                                      "rel": "self"
                                  },
                                  {
                                      "href": "http://ecx.images-amazon.com/images/I/31dGyu4hQJL._SL75_.jpg",
                                      "rel": "SmallImage"
                                  }
                              ]
                          },
                          {
                              "id": "B003Y6182G",
                              "type": "Chemical Hair Dyes",
                              "name": "L' Oreal Oreor 40-Volume Creme Developer",
                              "summary": "Beautiful, uniform color",
                              "brand": "L'Oreal Paris",
                              "links": [
                                  {
                                      "href": "https://localhost:8082/omni-channel-api/v1.0/items/B003Y6182G",
                                      "rel": "self"
                                  },
                                  {
                                      "href": "http://ecx.images-amazon.com/images/I/41GDOvgw1KL._SL75_.jpg",
                                      "rel": "SmallImage"
                                  }
                              ]
                          },
                          {
                              "id": "B004ECF7LC",
                              "type": "Chemical Hair Dyes",
                              "name": "L'Oreal Paris Excellence Crème with Pro-Keratine Complex",
                              "summary": "",
                              "brand": "L'Oreal Paris",
                              "links": [
                                  {
                                      "href": "https://localhost:8082/omni-channel-api/v1.0/items/B004ECF7LC",
                                      "rel": "self"
                                  },
                                  {
                                      "href": "http://ecx.images-amazon.com/images/I/21g%2B2DBWK1L._SL75_.jpg",
                                      "rel": "SmallImage"
                                  }
                              ]
                          }
                      ]
                  }
              }
  /{wish}:
    is: [personal]
    delete:
      description: Remove from wish list
/basket:
  is: [personal]
  description: All items ready for purchase
  get:
    is: [imageable]
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "collection" : {
                  "links" : [
                    { "rel" : "next", "href" : "http://alainn-cosmetics.cloudhub.io/api/v1.0/basket?pageIndex=20" },
                    { "rel" : "prev", "href" : "http://alainn-cosmetics.cloudhub.io/api/v1.0/basket?pageIndex=10" },
                    { "rel" : "self", "href" : "http://alainn-cosmetics.cloudhub.io/api/v1.0/basket" }
                  ],
                  "items" : [
                    {
                      "links" : [
                        { "rel" : "image", "href" : "" },
                        { "rel" : "self", "href" : "http://alainn-cosmetics.cloudhub.io/api/v1.0/basket/12341324" },
                        { "rel" : "parent", "href" : "http://alainn-cosmetics.cloudhub.io/api/v1.0/basket" }
                      ],
                      "id" : "12341324",
                      "type" : "Creams",
                      "name" : "Dove",
                      "summary" : "Soap! Just plain old soap!"
                      "sku" : "12344",
                      "price" : 1.00,
                      "stockQuantity" : 1,
                      "quantity" : 2
                    },
                    {
                      "links" : [
                        { "rel" : "image", "href" : "" },
                        { "rel" : "self", "href" : "http://alainn-cosmetics.cloudhub.io/api/v1.0/basket/09878623" }
                        { "rel" : "parent", "href" : "http://alainn-cosmetics.cloudhub.io/api/v1.0/basket" }                
                      ],
                      "id" : "09878623",
                      "type" : "Creams",
                      "name" : "Dove",
                      "summary" : "Soap! Just plain old soap!"
                      "sku" : "12344",
                      "price" : 1.00,
                      "stockQuantity" : 1,
                      "quantity" : 1
                    }
                  ]
                }
              }
  post:
    description: Add an Item to my Basket. Of course I may add more than 1 of the same Item.
    body:
      application/json:
        schema: basket-item
        example: |
          {
            "sku" : "B0000530ED",
            "quantity" : 2,
            "price" : 7.55
          }
  /checkout:
    is: [personal]
    type: controller
    description: Orders both pending and fulfilled
    post:
      body:
        application/json:
          example: &order-request-example |
           {
              "pickupLocation" : "Buenos Aires",
              "items" : [
                {
                  "sku" : "B003JTE8JS",
                  "price" : 7.50,
                  "quantity" : 3
                },
                {
                  "sku" : "B0000530ED",
                  "price" : 7.99,
                  "quantity" : 1
                }
              ]
            }
      responses: *postResponse
  /{item}:
    is: [personal]
    type: member
    put:
      description: Modify quantity
      body:
        application/json:
          schema: basket-item
          example: |
            {
              "sku" : "abc",
              "name" : "",
              "quantity" : 2
            }
    delete: 
      description: Remove from basket
/sales:
  is: [personal]
  type: collection
  description: Sales made at POS
  post:
    body:
      application/json:
        example: |
          {
            "items" : [
              {
                "sku" : "xyz",
                "quantity" : 3
              },
              {
                "sku" : "abc",
                "quantity" : 1
              }
            ]
          }
  /{sale}:
    is: [personal]
    type: member
    get:
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "date" : "2012-04-23",
                  "total" : 102.23,
                  "discount" : 2.77
                  "items" : [
                    {
                      "sku" : "abc",
                      "name" : "Channel No.5",
                      "price" : 25.00,
                      "quantity" : 2
                    },
                    {
                      "sku" : "axxxbc",
                      "name" : "Channel No.5",
                      "price" : 27.50,
                      "quantity" : 2
                    }
                  ]
                }
/registrations/{email}:
  type: controller
  post:
    body:
      application/json:
        schema: registration-request
        example: |
          {
            "firstName" : "Nial",
            "lastName" : "Darbey",
            "mobileNumber" : "134123423",
            "notificationPreferences" : [
              "email", "sms", "web", "mobile-push"
            ]
          }
  head:
    responses:
      200:
        description: Email found, therefore not available
      404:
        description: Email not found, therefore available
/mobile-tokens:
  is: [personal]
  type: collection
  post:
    body:
      application/json:
        example: |
          {
            "token" : "1234214"
          }
/my-profile:
  is: [personal]
  get:
    headers:
      email:
        type: string
        required: true
        example: nial.darbey@mulesoft.com
    responses:
      200:
        body:
          application/json:
            schema: my-profile
            example: |
              {
                "x-user-id" : "1",
                "firstName" : "Nial",
                "lastName" : "Darbey",
                "notificationPreferences" : [ "email", "mobile-push" ]
              }
/orders:
  is: [personal]
  type: read-only-collection
/pending-orders:
  is: [personal]
  type: read-only-collection
  /{order}: 
    is: [personal]
    type: member
    get:
      responses:
        200:
          body:
            application/json:
    delete:
      description: Cancel order
    patch:
      description: 'Modify part of Order: quantity of items, delivery address'  
/brands:
  get:
    is: [pageable]
    queryParameters:
      name:
        type: string
        required: false
        example: Deep Steep Honey Bubble Bath
    responses:
      200:
        body:
          application/json:
/categories:
  get:
    is: [pageable]
    queryParameters:
      name:
        type: string
        required: false
        example: Oils
    responses:
      200:
        body:
          application/json:
/top-items: &top-items
  type: read-only-collection
  get:
    is: [searchable]
  /{product}:
    type: { document : { schema : item } }
    /add-to-wish-list:
      type: controller
    /reviews:
      type: collection
/top-brands:
  type: read-only-collection
  description: x
  get:
    is: [searchable]
  /{brand}/top-items: *top-items
/recommendations:
  type: read-only-collection
  description: Recommended Products based on previous purchases
/promotions:
  type: read-only-collection
  get:
    is: [searchable]
  /{promotion}:
    type: { document : { schema : promotion } }
/returns:
  is: [personal]
  post:
    body:
      application/json:
        schema: return-request
        example: *order-request-example
    responses:
      202:
        description: Accepted
        headers:
          Location:
            type: string
            example: /returns/124243
  /{return}:
    is: [personal]
    type: { document: { schema: return-request } }
    /fulfill:
      type: controller